/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DdnConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DdnConfig{}

// DdnConfig struct for DdnConfig
type DdnConfig struct {
	// URL of the /sql endpoint on Hasura DDN
	Url string `json:"url"`
	// HTTP headers that should be forwarded to DDN
	Headers map[string]string `json:"headers,omitempty"`
}

type _DdnConfig DdnConfig

// NewDdnConfig instantiates a new DdnConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDdnConfig(url string) *DdnConfig {
	this := DdnConfig{}
	this.Url = url
	return &this
}

// NewDdnConfigWithDefaults instantiates a new DdnConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDdnConfigWithDefaults() *DdnConfig {
	this := DdnConfig{}
	return &this
}

// GetUrl returns the Url field value
func (o *DdnConfig) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *DdnConfig) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *DdnConfig) SetUrl(v string) {
	o.Url = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *DdnConfig) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DdnConfig) GetHeadersOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return map[string]string{}, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *DdnConfig) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *DdnConfig) SetHeaders(v map[string]string) {
	o.Headers = v
}

func (o DdnConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DdnConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	return toSerialize, nil
}

func (o *DdnConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDdnConfig := _DdnConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDdnConfig)

	if err != nil {
		return err
	}

	*o = DdnConfig(varDdnConfig)

	return err
}

type NullableDdnConfig struct {
	value *DdnConfig
	isSet bool
}

func (v NullableDdnConfig) Get() *DdnConfig {
	return v.value
}

func (v *NullableDdnConfig) Set(val *DdnConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDdnConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDdnConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDdnConfig(val *DdnConfig) *NullableDdnConfig {
	return &NullableDdnConfig{value: val, isSet: true}
}

func (v NullableDdnConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDdnConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


