/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiOpenAIConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiOpenAIConfig{}

// ApiOpenAIConfig struct for ApiOpenAIConfig
type ApiOpenAIConfig struct {
	Provider string `json:"provider"`
	Model NullableString `json:"model,omitempty"`
	BaseUrl NullableString `json:"base_url,omitempty"`
	ApiKey string `json:"api_key"`
}

type _ApiOpenAIConfig ApiOpenAIConfig

// NewApiOpenAIConfig instantiates a new ApiOpenAIConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiOpenAIConfig(provider string, apiKey string) *ApiOpenAIConfig {
	this := ApiOpenAIConfig{}
	this.Provider = provider
	this.ApiKey = apiKey
	return &this
}

// NewApiOpenAIConfigWithDefaults instantiates a new ApiOpenAIConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiOpenAIConfigWithDefaults() *ApiOpenAIConfig {
	this := ApiOpenAIConfig{}
	return &this
}

// GetProvider returns the Provider field value
func (o *ApiOpenAIConfig) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ApiOpenAIConfig) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ApiOpenAIConfig) SetProvider(v string) {
	o.Provider = v
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiOpenAIConfig) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiOpenAIConfig) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *ApiOpenAIConfig) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *ApiOpenAIConfig) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *ApiOpenAIConfig) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *ApiOpenAIConfig) UnsetModel() {
	o.Model.Unset()
}

// GetBaseUrl returns the BaseUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiOpenAIConfig) GetBaseUrl() string {
	if o == nil || IsNil(o.BaseUrl.Get()) {
		var ret string
		return ret
	}
	return *o.BaseUrl.Get()
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiOpenAIConfig) GetBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseUrl.Get(), o.BaseUrl.IsSet()
}

// HasBaseUrl returns a boolean if a field has been set.
func (o *ApiOpenAIConfig) HasBaseUrl() bool {
	if o != nil && o.BaseUrl.IsSet() {
		return true
	}

	return false
}

// SetBaseUrl gets a reference to the given NullableString and assigns it to the BaseUrl field.
func (o *ApiOpenAIConfig) SetBaseUrl(v string) {
	o.BaseUrl.Set(&v)
}
// SetBaseUrlNil sets the value for BaseUrl to be an explicit nil
func (o *ApiOpenAIConfig) SetBaseUrlNil() {
	o.BaseUrl.Set(nil)
}

// UnsetBaseUrl ensures that no value is present for BaseUrl, not even an explicit nil
func (o *ApiOpenAIConfig) UnsetBaseUrl() {
	o.BaseUrl.Unset()
}

// GetApiKey returns the ApiKey field value
func (o *ApiOpenAIConfig) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *ApiOpenAIConfig) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *ApiOpenAIConfig) SetApiKey(v string) {
	o.ApiKey = v
}

func (o ApiOpenAIConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiOpenAIConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.BaseUrl.IsSet() {
		toSerialize["base_url"] = o.BaseUrl.Get()
	}
	toSerialize["api_key"] = o.ApiKey
	return toSerialize, nil
}

func (o *ApiOpenAIConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiOpenAIConfig := _ApiOpenAIConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varApiOpenAIConfig)

	if err != nil {
		return err
	}

	*o = ApiOpenAIConfig(varApiOpenAIConfig)

	return err
}

type NullableApiOpenAIConfig struct {
	value *ApiOpenAIConfig
	isSet bool
}

func (v NullableApiOpenAIConfig) Get() *ApiOpenAIConfig {
	return v.value
}

func (v *NullableApiOpenAIConfig) Set(val *ApiOpenAIConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableApiOpenAIConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableApiOpenAIConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiOpenAIConfig(val *ApiOpenAIConfig) *NullableApiOpenAIConfig {
	return &NullableApiOpenAIConfig{value: val, isSet: true}
}

func (v NullableApiOpenAIConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiOpenAIConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

