/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Interaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Interaction{}

// Interaction struct for Interaction
type Interaction struct {
	UserMessage UserMessage `json:"user_message"`
	AssistantActions []AssistantAction `json:"assistant_actions,omitempty"`
}

type _Interaction Interaction

// NewInteraction instantiates a new Interaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInteraction(userMessage UserMessage) *Interaction {
	this := Interaction{}
	this.UserMessage = userMessage
	return &this
}

// NewInteractionWithDefaults instantiates a new Interaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInteractionWithDefaults() *Interaction {
	this := Interaction{}
	return &this
}

// GetUserMessage returns the UserMessage field value
func (o *Interaction) GetUserMessage() UserMessage {
	if o == nil {
		var ret UserMessage
		return ret
	}

	return o.UserMessage
}

// GetUserMessageOk returns a tuple with the UserMessage field value
// and a boolean to check if the value has been set.
func (o *Interaction) GetUserMessageOk() (*UserMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserMessage, true
}

// SetUserMessage sets field value
func (o *Interaction) SetUserMessage(v UserMessage) {
	o.UserMessage = v
}

// GetAssistantActions returns the AssistantActions field value if set, zero value otherwise.
func (o *Interaction) GetAssistantActions() []AssistantAction {
	if o == nil || IsNil(o.AssistantActions) {
		var ret []AssistantAction
		return ret
	}
	return o.AssistantActions
}

// GetAssistantActionsOk returns a tuple with the AssistantActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interaction) GetAssistantActionsOk() ([]AssistantAction, bool) {
	if o == nil || IsNil(o.AssistantActions) {
		return nil, false
	}
	return o.AssistantActions, true
}

// HasAssistantActions returns a boolean if a field has been set.
func (o *Interaction) HasAssistantActions() bool {
	if o != nil && !IsNil(o.AssistantActions) {
		return true
	}

	return false
}

// SetAssistantActions gets a reference to the given []AssistantAction and assigns it to the AssistantActions field.
func (o *Interaction) SetAssistantActions(v []AssistantAction) {
	o.AssistantActions = v
}

func (o Interaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Interaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_message"] = o.UserMessage
	if !IsNil(o.AssistantActions) {
		toSerialize["assistant_actions"] = o.AssistantActions
	}
	return toSerialize, nil
}

func (o *Interaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInteraction := _Interaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInteraction)

	if err != nil {
		return err
	}

	*o = Interaction(varInteraction)

	return err
}

type NullableInteraction struct {
	value *Interaction
	isSet bool
}

func (v NullableInteraction) Get() *Interaction {
	return v.value
}

func (v *NullableInteraction) Set(val *Interaction) {
	v.value = val
	v.isSet = true
}

func (v NullableInteraction) IsSet() bool {
	return v.isSet
}

func (v *NullableInteraction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInteraction(val *Interaction) *NullableInteraction {
	return &NullableInteraction{value: val, isSet: true}
}

func (v NullableInteraction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInteraction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


