/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TableArtifact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableArtifact{}

// TableArtifact struct for TableArtifact
type TableArtifact struct {
	Identifier string `json:"identifier"`
	Title string `json:"title"`
	ArtifactType string `json:"artifact_type"`
	// Table data as a list of objects, with the object keys being column names
	Data []map[string]interface{} `json:"data"`
}

type _TableArtifact TableArtifact

// NewTableArtifact instantiates a new TableArtifact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableArtifact(identifier string, title string, artifactType string, data []map[string]interface{}) *TableArtifact {
	this := TableArtifact{}
	this.Identifier = identifier
	this.Title = title
	this.ArtifactType = artifactType
	this.Data = data
	return &this
}

// NewTableArtifactWithDefaults instantiates a new TableArtifact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableArtifactWithDefaults() *TableArtifact {
	this := TableArtifact{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *TableArtifact) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *TableArtifact) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *TableArtifact) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTitle returns the Title field value
func (o *TableArtifact) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *TableArtifact) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *TableArtifact) SetTitle(v string) {
	o.Title = v
}

// GetArtifactType returns the ArtifactType field value
func (o *TableArtifact) GetArtifactType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArtifactType
}

// GetArtifactTypeOk returns a tuple with the ArtifactType field value
// and a boolean to check if the value has been set.
func (o *TableArtifact) GetArtifactTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArtifactType, true
}

// SetArtifactType sets field value
func (o *TableArtifact) SetArtifactType(v string) {
	o.ArtifactType = v
}

// GetData returns the Data field value
func (o *TableArtifact) GetData() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TableArtifact) GetDataOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *TableArtifact) SetData(v []map[string]interface{}) {
	o.Data = v
}

func (o TableArtifact) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableArtifact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	toSerialize["title"] = o.Title
	toSerialize["artifact_type"] = o.ArtifactType
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *TableArtifact) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
		"title",
		"artifact_type",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableArtifact := _TableArtifact{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTableArtifact)

	if err != nil {
		return err
	}

	*o = TableArtifact(varTableArtifact)

	return err
}

type NullableTableArtifact struct {
	value *TableArtifact
	isSet bool
}

func (v NullableTableArtifact) Get() *TableArtifact {
	return v.value
}

func (v *NullableTableArtifact) Set(val *TableArtifact) {
	v.value = val
	v.isSet = true
}

func (v NullableTableArtifact) IsSet() bool {
	return v.isSet
}

func (v *NullableTableArtifact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableArtifact(val *TableArtifact) *NullableTableArtifact {
	return &NullableTableArtifact{value: val, isSet: true}
}

func (v NullableTableArtifact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableArtifact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


