/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiThreadUserMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiThreadUserMessage{}

// ApiThreadUserMessage struct for ApiThreadUserMessage
type ApiThreadUserMessage struct {
	Text string `json:"text"`
}

type _ApiThreadUserMessage ApiThreadUserMessage

// NewApiThreadUserMessage instantiates a new ApiThreadUserMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiThreadUserMessage(text string) *ApiThreadUserMessage {
	this := ApiThreadUserMessage{}
	this.Text = text
	return &this
}

// NewApiThreadUserMessageWithDefaults instantiates a new ApiThreadUserMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiThreadUserMessageWithDefaults() *ApiThreadUserMessage {
	this := ApiThreadUserMessage{}
	return &this
}

// GetText returns the Text field value
func (o *ApiThreadUserMessage) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *ApiThreadUserMessage) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *ApiThreadUserMessage) SetText(v string) {
	o.Text = v
}

func (o ApiThreadUserMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiThreadUserMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *ApiThreadUserMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiThreadUserMessage := _ApiThreadUserMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiThreadUserMessage)

	if err != nil {
		return err
	}

	*o = ApiThreadUserMessage(varApiThreadUserMessage)

	return err
}

type NullableApiThreadUserMessage struct {
	value *ApiThreadUserMessage
	isSet bool
}

func (v NullableApiThreadUserMessage) Get() *ApiThreadUserMessage {
	return v.value
}

func (v *NullableApiThreadUserMessage) Set(val *ApiThreadUserMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableApiThreadUserMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableApiThreadUserMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiThreadUserMessage(val *ApiThreadUserMessage) *NullableApiThreadUserMessage {
	return &NullableApiThreadUserMessage{value: val, isSet: true}
}

func (v NullableApiThreadUserMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiThreadUserMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


