/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ApiThreadAssistantAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiThreadAssistantAction{}

// ApiThreadAssistantAction struct for ApiThreadAssistantAction
type ApiThreadAssistantAction struct {
	Message NullableString `json:"message,omitempty"`
	Plan NullableString `json:"plan,omitempty"`
	Code NullableString `json:"code,omitempty"`
	CodeOutput NullableString `json:"code_output,omitempty"`
	CodeError NullableString `json:"code_error,omitempty"`
}

// NewApiThreadAssistantAction instantiates a new ApiThreadAssistantAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiThreadAssistantAction() *ApiThreadAssistantAction {
	this := ApiThreadAssistantAction{}
	return &this
}

// NewApiThreadAssistantActionWithDefaults instantiates a new ApiThreadAssistantAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiThreadAssistantActionWithDefaults() *ApiThreadAssistantAction {
	this := ApiThreadAssistantAction{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiThreadAssistantAction) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiThreadAssistantAction) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *ApiThreadAssistantAction) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *ApiThreadAssistantAction) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *ApiThreadAssistantAction) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *ApiThreadAssistantAction) UnsetMessage() {
	o.Message.Unset()
}

// GetPlan returns the Plan field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiThreadAssistantAction) GetPlan() string {
	if o == nil || IsNil(o.Plan.Get()) {
		var ret string
		return ret
	}
	return *o.Plan.Get()
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiThreadAssistantAction) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Plan.Get(), o.Plan.IsSet()
}

// HasPlan returns a boolean if a field has been set.
func (o *ApiThreadAssistantAction) HasPlan() bool {
	if o != nil && o.Plan.IsSet() {
		return true
	}

	return false
}

// SetPlan gets a reference to the given NullableString and assigns it to the Plan field.
func (o *ApiThreadAssistantAction) SetPlan(v string) {
	o.Plan.Set(&v)
}
// SetPlanNil sets the value for Plan to be an explicit nil
func (o *ApiThreadAssistantAction) SetPlanNil() {
	o.Plan.Set(nil)
}

// UnsetPlan ensures that no value is present for Plan, not even an explicit nil
func (o *ApiThreadAssistantAction) UnsetPlan() {
	o.Plan.Unset()
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiThreadAssistantAction) GetCode() string {
	if o == nil || IsNil(o.Code.Get()) {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiThreadAssistantAction) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *ApiThreadAssistantAction) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *ApiThreadAssistantAction) SetCode(v string) {
	o.Code.Set(&v)
}
// SetCodeNil sets the value for Code to be an explicit nil
func (o *ApiThreadAssistantAction) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *ApiThreadAssistantAction) UnsetCode() {
	o.Code.Unset()
}

// GetCodeOutput returns the CodeOutput field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiThreadAssistantAction) GetCodeOutput() string {
	if o == nil || IsNil(o.CodeOutput.Get()) {
		var ret string
		return ret
	}
	return *o.CodeOutput.Get()
}

// GetCodeOutputOk returns a tuple with the CodeOutput field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiThreadAssistantAction) GetCodeOutputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CodeOutput.Get(), o.CodeOutput.IsSet()
}

// HasCodeOutput returns a boolean if a field has been set.
func (o *ApiThreadAssistantAction) HasCodeOutput() bool {
	if o != nil && o.CodeOutput.IsSet() {
		return true
	}

	return false
}

// SetCodeOutput gets a reference to the given NullableString and assigns it to the CodeOutput field.
func (o *ApiThreadAssistantAction) SetCodeOutput(v string) {
	o.CodeOutput.Set(&v)
}
// SetCodeOutputNil sets the value for CodeOutput to be an explicit nil
func (o *ApiThreadAssistantAction) SetCodeOutputNil() {
	o.CodeOutput.Set(nil)
}

// UnsetCodeOutput ensures that no value is present for CodeOutput, not even an explicit nil
func (o *ApiThreadAssistantAction) UnsetCodeOutput() {
	o.CodeOutput.Unset()
}

// GetCodeError returns the CodeError field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiThreadAssistantAction) GetCodeError() string {
	if o == nil || IsNil(o.CodeError.Get()) {
		var ret string
		return ret
	}
	return *o.CodeError.Get()
}

// GetCodeErrorOk returns a tuple with the CodeError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiThreadAssistantAction) GetCodeErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CodeError.Get(), o.CodeError.IsSet()
}

// HasCodeError returns a boolean if a field has been set.
func (o *ApiThreadAssistantAction) HasCodeError() bool {
	if o != nil && o.CodeError.IsSet() {
		return true
	}

	return false
}

// SetCodeError gets a reference to the given NullableString and assigns it to the CodeError field.
func (o *ApiThreadAssistantAction) SetCodeError(v string) {
	o.CodeError.Set(&v)
}
// SetCodeErrorNil sets the value for CodeError to be an explicit nil
func (o *ApiThreadAssistantAction) SetCodeErrorNil() {
	o.CodeError.Set(nil)
}

// UnsetCodeError ensures that no value is present for CodeError, not even an explicit nil
func (o *ApiThreadAssistantAction) UnsetCodeError() {
	o.CodeError.Unset()
}

func (o ApiThreadAssistantAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiThreadAssistantAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	if o.Plan.IsSet() {
		toSerialize["plan"] = o.Plan.Get()
	}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	if o.CodeOutput.IsSet() {
		toSerialize["code_output"] = o.CodeOutput.Get()
	}
	if o.CodeError.IsSet() {
		toSerialize["code_error"] = o.CodeError.Get()
	}
	return toSerialize, nil
}

type NullableApiThreadAssistantAction struct {
	value *ApiThreadAssistantAction
	isSet bool
}

func (v NullableApiThreadAssistantAction) Get() *ApiThreadAssistantAction {
	return v.value
}

func (v *NullableApiThreadAssistantAction) Set(val *ApiThreadAssistantAction) {
	v.value = val
	v.isSet = true
}

func (v NullableApiThreadAssistantAction) IsSet() bool {
	return v.isSet
}

func (v *NullableApiThreadAssistantAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiThreadAssistantAction(val *ApiThreadAssistantAction) *NullableApiThreadAssistantAction {
	return &NullableApiThreadAssistantAction{value: val, isSet: true}
}

func (v NullableApiThreadAssistantAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiThreadAssistantAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

