/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExecuteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteRequest{}

// ExecuteRequest struct for ExecuteRequest
type ExecuteRequest struct {
	Code string `json:"code"`
	PromptqlApiKey NullableString `json:"promptql_api_key,omitempty"`
	AiPrimitivesLlm NullableExecuteRequestAiPrimitivesLlm `json:"ai_primitives_llm"`
	Ddn NullableDdnConfig `json:"ddn"`
	Artifacts []ExecuteRequestArtifactsInner `json:"artifacts"`
}

type _ExecuteRequest ExecuteRequest

// NewExecuteRequest instantiates a new ExecuteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteRequest(code string, aiPrimitivesLlm NullableExecuteRequestAiPrimitivesLlm, ddn NullableDdnConfig, artifacts []ExecuteRequestArtifactsInner) *ExecuteRequest {
	this := ExecuteRequest{}
	this.Code = code
	this.AiPrimitivesLlm = aiPrimitivesLlm
	this.Ddn = ddn
	this.Artifacts = artifacts
	return &this
}

// NewExecuteRequestWithDefaults instantiates a new ExecuteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteRequestWithDefaults() *ExecuteRequest {
	this := ExecuteRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *ExecuteRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ExecuteRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ExecuteRequest) SetCode(v string) {
	o.Code = v
}

// GetPromptqlApiKey returns the PromptqlApiKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExecuteRequest) GetPromptqlApiKey() string {
	if o == nil || IsNil(o.PromptqlApiKey.Get()) {
		var ret string
		return ret
	}
	return *o.PromptqlApiKey.Get()
}

// GetPromptqlApiKeyOk returns a tuple with the PromptqlApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecuteRequest) GetPromptqlApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromptqlApiKey.Get(), o.PromptqlApiKey.IsSet()
}

// HasPromptqlApiKey returns a boolean if a field has been set.
func (o *ExecuteRequest) HasPromptqlApiKey() bool {
	if o != nil && o.PromptqlApiKey.IsSet() {
		return true
	}

	return false
}

// SetPromptqlApiKey gets a reference to the given NullableString and assigns it to the PromptqlApiKey field.
func (o *ExecuteRequest) SetPromptqlApiKey(v string) {
	o.PromptqlApiKey.Set(&v)
}
// SetPromptqlApiKeyNil sets the value for PromptqlApiKey to be an explicit nil
func (o *ExecuteRequest) SetPromptqlApiKeyNil() {
	o.PromptqlApiKey.Set(nil)
}

// UnsetPromptqlApiKey ensures that no value is present for PromptqlApiKey, not even an explicit nil
func (o *ExecuteRequest) UnsetPromptqlApiKey() {
	o.PromptqlApiKey.Unset()
}

// GetAiPrimitivesLlm returns the AiPrimitivesLlm field value
// If the value is explicit nil, the zero value for ExecuteRequestAiPrimitivesLlm will be returned
func (o *ExecuteRequest) GetAiPrimitivesLlm() ExecuteRequestAiPrimitivesLlm {
	if o == nil || o.AiPrimitivesLlm.Get() == nil {
		var ret ExecuteRequestAiPrimitivesLlm
		return ret
	}

	return *o.AiPrimitivesLlm.Get()
}

// GetAiPrimitivesLlmOk returns a tuple with the AiPrimitivesLlm field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecuteRequest) GetAiPrimitivesLlmOk() (*ExecuteRequestAiPrimitivesLlm, bool) {
	if o == nil {
		return nil, false
	}
	return o.AiPrimitivesLlm.Get(), o.AiPrimitivesLlm.IsSet()
}

// SetAiPrimitivesLlm sets field value
func (o *ExecuteRequest) SetAiPrimitivesLlm(v ExecuteRequestAiPrimitivesLlm) {
	o.AiPrimitivesLlm.Set(&v)
}

// GetDdn returns the Ddn field value
// If the value is explicit nil, the zero value for DdnConfig will be returned
func (o *ExecuteRequest) GetDdn() DdnConfig {
	if o == nil || o.Ddn.Get() == nil {
		var ret DdnConfig
		return ret
	}

	return *o.Ddn.Get()
}

// GetDdnOk returns a tuple with the Ddn field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecuteRequest) GetDdnOk() (*DdnConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ddn.Get(), o.Ddn.IsSet()
}

// SetDdn sets field value
func (o *ExecuteRequest) SetDdn(v DdnConfig) {
	o.Ddn.Set(&v)
}

// GetArtifacts returns the Artifacts field value
func (o *ExecuteRequest) GetArtifacts() []ExecuteRequestArtifactsInner {
	if o == nil {
		var ret []ExecuteRequestArtifactsInner
		return ret
	}

	return o.Artifacts
}

// GetArtifactsOk returns a tuple with the Artifacts field value
// and a boolean to check if the value has been set.
func (o *ExecuteRequest) GetArtifactsOk() ([]ExecuteRequestArtifactsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Artifacts, true
}

// SetArtifacts sets field value
func (o *ExecuteRequest) SetArtifacts(v []ExecuteRequestArtifactsInner) {
	o.Artifacts = v
}

func (o ExecuteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecuteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if o.PromptqlApiKey.IsSet() {
		toSerialize["promptql_api_key"] = o.PromptqlApiKey.Get()
	}
	toSerialize["ai_primitives_llm"] = o.AiPrimitivesLlm.Get()
	toSerialize["ddn"] = o.Ddn.Get()
	toSerialize["artifacts"] = o.Artifacts
	return toSerialize, nil
}

func (o *ExecuteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"ai_primitives_llm",
		"ddn",
		"artifacts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExecuteRequest := _ExecuteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExecuteRequest)

	if err != nil {
		return err
	}

	*o = ExecuteRequest(varExecuteRequest)

	return err
}

type NullableExecuteRequest struct {
	value *ExecuteRequest
	isSet bool
}

func (v NullableExecuteRequest) Get() *ExecuteRequest {
	return v.value
}

func (v *NullableExecuteRequest) Set(val *ExecuteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteRequest(val *ExecuteRequest) *NullableExecuteRequest {
	return &NullableExecuteRequest{value: val, isSet: true}
}

func (v NullableExecuteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


