/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HasuraLlmConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HasuraLlmConfig{}

// HasuraLlmConfig struct for HasuraLlmConfig
type HasuraLlmConfig struct {
	Provider string `json:"provider"`
}

type _HasuraLlmConfig HasuraLlmConfig

// NewHasuraLlmConfig instantiates a new HasuraLlmConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHasuraLlmConfig(provider string) *HasuraLlmConfig {
	this := HasuraLlmConfig{}
	this.Provider = provider
	return &this
}

// NewHasuraLlmConfigWithDefaults instantiates a new HasuraLlmConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHasuraLlmConfigWithDefaults() *HasuraLlmConfig {
	this := HasuraLlmConfig{}
	return &this
}

// GetProvider returns the Provider field value
func (o *HasuraLlmConfig) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *HasuraLlmConfig) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *HasuraLlmConfig) SetProvider(v string) {
	o.Provider = v
}

func (o HasuraLlmConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HasuraLlmConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	return toSerialize, nil
}

func (o *HasuraLlmConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHasuraLlmConfig := _HasuraLlmConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varHasuraLlmConfig)

	if err != nil {
		return err
	}

	*o = HasuraLlmConfig(varHasuraLlmConfig)

	return err
}

type NullableHasuraLlmConfig struct {
	value *HasuraLlmConfig
	isSet bool
}

func (v NullableHasuraLlmConfig) Get() *HasuraLlmConfig {
	return v.value
}

func (v *NullableHasuraLlmConfig) Set(val *HasuraLlmConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableHasuraLlmConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableHasuraLlmConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHasuraLlmConfig(val *HasuraLlmConfig) *NullableHasuraLlmConfig {
	return &NullableHasuraLlmConfig{value: val, isSet: true}
}

func (v NullableHasuraLlmConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHasuraLlmConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

