/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ErrorChunk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorChunk{}

// ErrorChunk struct for ErrorChunk
type ErrorChunk struct {
	Type string `json:"type"`
	Error string `json:"error"`
}

type _ErrorChunk ErrorChunk

// NewErrorChunk instantiates a new ErrorChunk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorChunk(type_ string, error_ string) *ErrorChunk {
	this := ErrorChunk{}
	this.Type = type_
	this.Error = error_
	return &this
}

// NewErrorChunkWithDefaults instantiates a new ErrorChunk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorChunkWithDefaults() *ErrorChunk {
	this := ErrorChunk{}
	return &this
}

// GetType returns the Type field value
func (o *ErrorChunk) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ErrorChunk) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ErrorChunk) SetType(v string) {
	o.Type = v
}

// GetError returns the Error field value
func (o *ErrorChunk) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ErrorChunk) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ErrorChunk) SetError(v string) {
	o.Error = v
}

func (o ErrorChunk) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorChunk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *ErrorChunk) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorChunk := _ErrorChunk{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varErrorChunk)

	if err != nil {
		return err
	}

	*o = ErrorChunk(varErrorChunk)

	return err
}

type NullableErrorChunk struct {
	value *ErrorChunk
	isSet bool
}

func (v NullableErrorChunk) Get() *ErrorChunk {
	return v.value
}

func (v *NullableErrorChunk) Set(val *ErrorChunk) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorChunk) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorChunk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorChunk(val *ErrorChunk) *NullableErrorChunk {
	return &NullableErrorChunk{value: val, isSet: true}
}

func (v NullableErrorChunk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorChunk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

