/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryRequest{}

// QueryRequest struct for QueryRequest
type QueryRequest struct {
	Version string `json:"version"`
	PromptqlApiKey NullableString `json:"promptql_api_key,omitempty"`
	Llm *Llm `json:"llm,omitempty"`
	AiPrimitivesLlm NullableExecuteRequestAiPrimitivesLlm `json:"ai_primitives_llm,omitempty"`
	Ddn DdnConfig `json:"ddn"`
	Artifacts []ExecuteRequestArtifactsInner `json:"artifacts,omitempty"`
	SystemInstructions NullableString `json:"system_instructions,omitempty"`
	// An IANA timezone used to interpret queries that implicitly require timezones
	Timezone string `json:"timezone"`
	Interactions []ApiThreadInteraction `json:"interactions"`
	Stream bool `json:"stream"`
}

type _QueryRequest QueryRequest

// NewQueryRequest instantiates a new QueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryRequest(version string, ddn DdnConfig, timezone string, interactions []ApiThreadInteraction, stream bool) *QueryRequest {
	this := QueryRequest{}
	this.Version = version
	this.Ddn = ddn
	this.Timezone = timezone
	this.Interactions = interactions
	this.Stream = stream
	return &this
}

// NewQueryRequestWithDefaults instantiates a new QueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryRequestWithDefaults() *QueryRequest {
	this := QueryRequest{}
	return &this
}

// GetVersion returns the Version field value
func (o *QueryRequest) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *QueryRequest) SetVersion(v string) {
	o.Version = v
}

// GetPromptqlApiKey returns the PromptqlApiKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetPromptqlApiKey() string {
	if o == nil || IsNil(o.PromptqlApiKey.Get()) {
		var ret string
		return ret
	}
	return *o.PromptqlApiKey.Get()
}

// GetPromptqlApiKeyOk returns a tuple with the PromptqlApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetPromptqlApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromptqlApiKey.Get(), o.PromptqlApiKey.IsSet()
}

// HasPromptqlApiKey returns a boolean if a field has been set.
func (o *QueryRequest) HasPromptqlApiKey() bool {
	if o != nil && o.PromptqlApiKey.IsSet() {
		return true
	}

	return false
}

// SetPromptqlApiKey gets a reference to the given NullableString and assigns it to the PromptqlApiKey field.
func (o *QueryRequest) SetPromptqlApiKey(v string) {
	o.PromptqlApiKey.Set(&v)
}
// SetPromptqlApiKeyNil sets the value for PromptqlApiKey to be an explicit nil
func (o *QueryRequest) SetPromptqlApiKeyNil() {
	o.PromptqlApiKey.Set(nil)
}

// UnsetPromptqlApiKey ensures that no value is present for PromptqlApiKey, not even an explicit nil
func (o *QueryRequest) UnsetPromptqlApiKey() {
	o.PromptqlApiKey.Unset()
}

// GetLlm returns the Llm field value if set, zero value otherwise.
func (o *QueryRequest) GetLlm() Llm {
	if o == nil || IsNil(o.Llm) {
		var ret Llm
		return ret
	}
	return *o.Llm
}

// GetLlmOk returns a tuple with the Llm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetLlmOk() (*Llm, bool) {
	if o == nil || IsNil(o.Llm) {
		return nil, false
	}
	return o.Llm, true
}

// HasLlm returns a boolean if a field has been set.
func (o *QueryRequest) HasLlm() bool {
	if o != nil && !IsNil(o.Llm) {
		return true
	}

	return false
}

// SetLlm gets a reference to the given Llm and assigns it to the Llm field.
func (o *QueryRequest) SetLlm(v Llm) {
	o.Llm = &v
}

// GetAiPrimitivesLlm returns the AiPrimitivesLlm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetAiPrimitivesLlm() ExecuteRequestAiPrimitivesLlm {
	if o == nil || IsNil(o.AiPrimitivesLlm.Get()) {
		var ret ExecuteRequestAiPrimitivesLlm
		return ret
	}
	return *o.AiPrimitivesLlm.Get()
}

// GetAiPrimitivesLlmOk returns a tuple with the AiPrimitivesLlm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetAiPrimitivesLlmOk() (*ExecuteRequestAiPrimitivesLlm, bool) {
	if o == nil {
		return nil, false
	}
	return o.AiPrimitivesLlm.Get(), o.AiPrimitivesLlm.IsSet()
}

// HasAiPrimitivesLlm returns a boolean if a field has been set.
func (o *QueryRequest) HasAiPrimitivesLlm() bool {
	if o != nil && o.AiPrimitivesLlm.IsSet() {
		return true
	}

	return false
}

// SetAiPrimitivesLlm gets a reference to the given NullableExecuteRequestAiPrimitivesLlm and assigns it to the AiPrimitivesLlm field.
func (o *QueryRequest) SetAiPrimitivesLlm(v ExecuteRequestAiPrimitivesLlm) {
	o.AiPrimitivesLlm.Set(&v)
}
// SetAiPrimitivesLlmNil sets the value for AiPrimitivesLlm to be an explicit nil
func (o *QueryRequest) SetAiPrimitivesLlmNil() {
	o.AiPrimitivesLlm.Set(nil)
}

// UnsetAiPrimitivesLlm ensures that no value is present for AiPrimitivesLlm, not even an explicit nil
func (o *QueryRequest) UnsetAiPrimitivesLlm() {
	o.AiPrimitivesLlm.Unset()
}

// GetDdn returns the Ddn field value
func (o *QueryRequest) GetDdn() DdnConfig {
	if o == nil {
		var ret DdnConfig
		return ret
	}

	return o.Ddn
}

// GetDdnOk returns a tuple with the Ddn field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetDdnOk() (*DdnConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ddn, true
}

// SetDdn sets field value
func (o *QueryRequest) SetDdn(v DdnConfig) {
	o.Ddn = v
}

// GetArtifacts returns the Artifacts field value if set, zero value otherwise.
func (o *QueryRequest) GetArtifacts() []ExecuteRequestArtifactsInner {
	if o == nil || IsNil(o.Artifacts) {
		var ret []ExecuteRequestArtifactsInner
		return ret
	}
	return o.Artifacts
}

// GetArtifactsOk returns a tuple with the Artifacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetArtifactsOk() ([]ExecuteRequestArtifactsInner, bool) {
	if o == nil || IsNil(o.Artifacts) {
		return nil, false
	}
	return o.Artifacts, true
}

// HasArtifacts returns a boolean if a field has been set.
func (o *QueryRequest) HasArtifacts() bool {
	if o != nil && !IsNil(o.Artifacts) {
		return true
	}

	return false
}

// SetArtifacts gets a reference to the given []ExecuteRequestArtifactsInner and assigns it to the Artifacts field.
func (o *QueryRequest) SetArtifacts(v []ExecuteRequestArtifactsInner) {
	o.Artifacts = v
}

// GetSystemInstructions returns the SystemInstructions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetSystemInstructions() string {
	if o == nil || IsNil(o.SystemInstructions.Get()) {
		var ret string
		return ret
	}
	return *o.SystemInstructions.Get()
}

// GetSystemInstructionsOk returns a tuple with the SystemInstructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetSystemInstructionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SystemInstructions.Get(), o.SystemInstructions.IsSet()
}

// HasSystemInstructions returns a boolean if a field has been set.
func (o *QueryRequest) HasSystemInstructions() bool {
	if o != nil && o.SystemInstructions.IsSet() {
		return true
	}

	return false
}

// SetSystemInstructions gets a reference to the given NullableString and assigns it to the SystemInstructions field.
func (o *QueryRequest) SetSystemInstructions(v string) {
	o.SystemInstructions.Set(&v)
}
// SetSystemInstructionsNil sets the value for SystemInstructions to be an explicit nil
func (o *QueryRequest) SetSystemInstructionsNil() {
	o.SystemInstructions.Set(nil)
}

// UnsetSystemInstructions ensures that no value is present for SystemInstructions, not even an explicit nil
func (o *QueryRequest) UnsetSystemInstructions() {
	o.SystemInstructions.Unset()
}

// GetTimezone returns the Timezone field value
func (o *QueryRequest) GetTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timezone, true
}

// SetTimezone sets field value
func (o *QueryRequest) SetTimezone(v string) {
	o.Timezone = v
}

// GetInteractions returns the Interactions field value
func (o *QueryRequest) GetInteractions() []ApiThreadInteraction {
	if o == nil {
		var ret []ApiThreadInteraction
		return ret
	}

	return o.Interactions
}

// GetInteractionsOk returns a tuple with the Interactions field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetInteractionsOk() ([]ApiThreadInteraction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Interactions, true
}

// SetInteractions sets field value
func (o *QueryRequest) SetInteractions(v []ApiThreadInteraction) {
	o.Interactions = v
}

// GetStream returns the Stream field value
func (o *QueryRequest) GetStream() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Stream
}

// GetStreamOk returns a tuple with the Stream field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetStreamOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stream, true
}

// SetStream sets field value
func (o *QueryRequest) SetStream(v bool) {
	o.Stream = v
}

func (o QueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	if o.PromptqlApiKey.IsSet() {
		toSerialize["promptql_api_key"] = o.PromptqlApiKey.Get()
	}
	if !IsNil(o.Llm) {
		toSerialize["llm"] = o.Llm
	}
	if o.AiPrimitivesLlm.IsSet() {
		toSerialize["ai_primitives_llm"] = o.AiPrimitivesLlm.Get()
	}
	toSerialize["ddn"] = o.Ddn
	if !IsNil(o.Artifacts) {
		toSerialize["artifacts"] = o.Artifacts
	}
	if o.SystemInstructions.IsSet() {
		toSerialize["system_instructions"] = o.SystemInstructions.Get()
	}
	toSerialize["timezone"] = o.Timezone
	toSerialize["interactions"] = o.Interactions
	toSerialize["stream"] = o.Stream
	return toSerialize, nil
}

func (o *QueryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"ddn",
		"timezone",
		"interactions",
		"stream",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryRequest := _QueryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryRequest)

	if err != nil {
		return err
	}

	*o = QueryRequest(varQueryRequest)

	return err
}

type NullableQueryRequest struct {
	value *QueryRequest
	isSet bool
}

func (v NullableQueryRequest) Get() *QueryRequest {
	return v.value
}

func (v *NullableQueryRequest) Set(val *QueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryRequest(val *QueryRequest) *NullableQueryRequest {
	return &NullableQueryRequest{value: val, isSet: true}
}

func (v NullableQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


