/*
PromptQL API

PromptQL API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserMessage{}

// UserMessage struct for UserMessage
type UserMessage struct {
	Text string `json:"text"`
}

type _UserMessage UserMessage

// NewUserMessage instantiates a new UserMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserMessage(text string) *UserMessage {
	this := UserMessage{}
	this.Text = text
	return &this
}

// NewUserMessageWithDefaults instantiates a new UserMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserMessageWithDefaults() *UserMessage {
	this := UserMessage{}
	return &this
}

// GetText returns the Text field value
func (o *UserMessage) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *UserMessage) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *UserMessage) SetText(v string) {
	o.Text = v
}

func (o UserMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *UserMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserMessage := _UserMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserMessage)

	if err != nil {
		return err
	}

	*o = UserMessage(varUserMessage)

	return err
}

type NullableUserMessage struct {
	value *UserMessage
	isSet bool
}

func (v NullableUserMessage) Get() *UserMessage {
	return v.value
}

func (v *NullableUserMessage) Set(val *UserMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableUserMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableUserMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserMessage(val *UserMessage) *NullableUserMessage {
	return &NullableUserMessage{value: val, isSet: true}
}

func (v NullableUserMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


